spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:21333/postgres
    username: postgres
  jpa:
    generateDdl: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    static-path-pattern: /
    throw-exception-if-no-handler-found: true

logging:
  pattern:
  level:
    org.hibernate:
      SQL: debug