spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:22222/postgres
    username: postgres
  jpa:
    generateDdl: true
    hibernate:
      ddl-auto: update
github:
  api-url: https://api.github.com/users