version: '3.7'
services:
  api-call-counter:
    container_name: api-call-counter
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '22222:5432'
